# This creates a copy of the database URL secret in the application namespace
# Apply this after setting up PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: postgres-connection
  namespace: quotesdb
  labels:
    app: quotesdb
    component: database-connection
type: Opaque
stringData:
  DATABASE_URL: "postgresql://quotesdb:changeme-production-password@postgres-service.postgres.svc.cluster.local:5432/quotesdb"