apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_PASSWORD: "changeme-production-password"  # CHANGE THIS!
  POSTGRES_REPLICATION_PASSWORD: "changeme-replication-password"  # CHANGE THIS!
  
  # Connection string for applications
  DATABASE_URL: "postgresql://quotesdb:changeme-production-password@postgres-service.postgres.svc.cluster.local:5432/quotesdb"