apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage
  labels:
    app: postgres
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  encrypted: "true"
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer